server_url: http://127.0.0.1:8080
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090
grpc_listen_addr: 0.0.0.0:9090
grpc_allow_insecure: false
private_key_path: /var/lib/headscale/private.key
noise:
  private_key_path: /var/lib/headscale/noise_private.key
base_domain: headscale.internal
ephemeral_node_inactivity_timeout: 30m
node_update_check_interval: 10s
db_type: sqlite3
db_path: /var/lib/headscale/db.sqlite
acme_url: https://acme-v02.api.letsencrypt.org/directory
acme_email: ""
logs:
  format: text
  level: info
dns:
  base_ip: 100.64.0.1
  nameservers:
    - 1.1.1.1
    - 1.0.0.1
  magic_dns: true
  base_domain: headscale.internal
unix_socket: /var/lib/headscale/headscale.sock
unix_socket_permission: "0770"
grpc_socket_permission: "0770"