version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: madutxo-headscale_headplane_1
      APP_PORT: 3000

  headscale:
    image: headscale/headscale:v0.28
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/headscale:rw

  headplane:
    image: ghcr.io/tale/headplane:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "3000:3000"
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/headscale:rw
    environment:
      - TZ=${TZ:-UTC}
      - HEADPLANE_LOAD_ENV_OVERRIDES=true
      - HEADPLANE_HEADSCALE__URL=http://127.0.0.1:8080
      - HEADPLANE_HEADSCALE__API_KEY_PATH=/var/lib/headscale/api_key.txt
      - HEADPLANE_SERVER__COOKIE_SECRET_PATH=/var/lib/headscale/cookie_secret

volumes:
  data:
