version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: madutxo-libretranslate_main_1
      APP_PORT: 5000
      PROXY_AUTH_ADD: "false"

  main:
    image: libretranslate/libretranslate:v1.6.5@sha256:a3518195e4e810ba0d9dd251a851f24918059d757ef3c5cf8e0f881daf4242fc
    user: "1000:1000"
    init: true
    restart: unless-stopped
    stop_grace_period: 1m
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD-SHELL", "./venv/bin/python scripts/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - TZ=${TZ:-UTC}
      - LT_LOAD_ONLY=en,es,fr,de,it,pt
    volumes:
      - ${APP_DATA_DIR}/data:/data:rw
