server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://madutxo-liquid-electrs_electrs_1:3000/;
        proxy_set_header Host $host;
        add_header Cache-Control "no-cache";
    }

    location = /tor-address {
        alias /tor/app-madutxo-liquid-electrs/main/hostname;
        add_header Cache-Control "no-cache";
        # If hostname not yet generated (tor bootstrapping), return 204 instead of 404
        error_page 404 =204 /empty;
    }
    location = /empty {
        return 204;
    }
}


