name: Build electrs-liquid

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'Dockerfile.electrs-liquid'
      - 'compact-headers.patch'
      - 'entrypoint.sh'
      - '.github/workflows/build-electrs-liquid.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Log in to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT || secrets.GITHUB_TOKEN }}

      - name: Build and push 0.6.1
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          file: ./Dockerfile.electrs-liquid
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/madutxo/electrs-liquid:0.6.1
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
